### ISSUE TITLE
sphinx is an unnecessary requirement

### ISSUE THREAD

**Issue by Doggie52** [ig-python/ig-markets-api-python-library#228]
Not sure when this happened, but suddenly `sphinx` is a requirement for this project. At least, when I run `pip-compile --upgrade`, I am seeing the following new requirements:

```
snowballstemmer==2.1.0
    # via sphinx
sphinx==4.2.0
    # via sphinx-rtd-theme
sphinx-rtd-theme==0.5.2
    # via trading-ig
sphinxcontrib-applehelp==1.0.2
    # via sphinx
sphinxcontrib-devhelp==1.0.2
    # via sphinx
sphinxcontrib-htmlhelp==2.0.0
    # via sphinx
sphinxcontrib-jsmath==1.0.1
    # via sphinx
sphinxcontrib-qthelp==1.0.3
    # via sphinx
sphinxcontrib-serializinghtml==1.1.5
    # via sphinx
```

I don't think sphinx should be necessary for running this library, and frankly is not a package I'm super happy to be adding as a requirement for my project.

Is this perhaps a mistake on my end? I can't really see where the `sphinx` requirement is coming in, other than in https://github.com/ig-python/ig-markets-api-python-library/blob/master/pyproject.toml .

**Comment by bug-or-feature** [comment]
Hi @Doggie52, you're right Sphinx should not be included for most users; that is why it is an optional dependency in pyproject.toml.

If you can tell me a little about your project setup, I can try to resolve. How did you install trading_ig? Is your project a fork of this one, or a separate project with this one as a dependency? If the latter, how is the dependency expressed?

**Comment by Doggie52** [comment]
Hi @bug-or-feature, it's quite simple. I'm just adding adding a line containing `trading_ig` to my `requirements.in` file which I then parse into a `txt` file using `pip-compile requirements.in --upgrade`.

**Comment by bug-or-feature** [comment]
@Doggie52 thanks. I'll look into this

**Comment by Doggie52** [comment]
Sure thing - let me know if you need any more info.

**Comment by Doggie52** [comment]
This seems to have happened in `0.0.12` - if I pin to `0.0.11` I don't get the `sphinx` requirements added.

**Comment by bug-or-feature** [comment]
fixed by the latest release 0.0.13

**Comment by Doggie52** [comment]
Thank you!

Oddly enough I see now `munch` has disappeared from my requirements after updating from `0.0.11` to `0.0.13`. Any ideas why? Should it be gone? I still see it in the project's `requirements.txt` so I'm worried it should remain.

Don't want to submit another issue for it in case it's nothing to worry about.

**Comment by Doggie52** [comment]
Looks like my tests are failing, so it looks like it shouldn't be gone.

**Comment by Doggie52** [comment]
It seems the `requirements.txt` file is no longer being honoured in the package.

**Comment by bug-or-feature** [comment]
Please read the docs, especially the [quickstart](https://trading-ig.readthedocs.io/en/latest/quickstart.html) regarding optional packages, [this FAQ item](https://trading-ig.readthedocs.io/en/latest/faq.html#why-are-there-both-setup-py-and-pyproject-toml-files), and [this one](https://trading-ig.readthedocs.io/en/latest/faq.html#why-is-pandas-an-optional-dependency-in-pyproject-toml) - munch is optional, like pandas

**Comment by Doggie52** [comment]
`munch` is not optional - it's imported in `rest.py`. Currently, doing `pip install trading_ig` does not install `munch`, so this will never work.

**Comment by Doggie52** [comment]
It's possible there are things in this library that don't use `munch` but I struggle to see how you can get much done without it.
